server:
  port: 8080

spring:
  application:
    name: taotaomall
  datasource:
    url: jdbc:mysql://localhost/taotaobusiness?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: taotaomall.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  SING: "ptu11380925"
  expireTime: 30

pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countsql

file:
  save-path: "F:/dianshang(6)/dianshang/TaotaoBackend/backend/src/main/resources/static/images/"
image:
  prefix-url: "http://localhost:8080/images/"